<?php

const PENDING_PRODUCT=   0;
const REJECTED_PRODUCT = 1;
const APPROVED_PRODUCT = 2;
const ON_THE_WAY = 3;


const ISSUE_FULL_QUANTITY  =   1;
const ISSUE_PARTIAL_QUANTITY = 2;
const ISSUE_BALANCE_QUANTITY = 3;
